import numpy as np
import matplotlib.pyplot as plt

x=np.linspace(-5, 5, 100)
plt.subplot(221)
y=x
plt.title('y=x')                      
plt.xlabel('x')                                                 
plt.ylabel('y') 
plt.plot(x, y)
plt.subplot(222)
x=np.linspace(-np.pi, np.pi, 100)
y=np.sin(x)
plt.title('y=sin(x)')                      
plt.xlabel('x')                                                 
plt.ylabel('y') 
plt.plot(x, y)
plt.subplot(223)
x=np.linspace(-3, 3, 100)
y=np.exp(x)
plt.title('y=e**x')                      
plt.xlabel('x')                                                 
plt.ylabel('y') 
plt.plot(x, y)
plt.subplot(224)
x=np.linspace(0.001, 10, 100)
y=np.log(x)
plt.title('y=log(x)')                      
plt.xlabel('x')                                                 
plt.ylabel('y') 
plt.plot(x, y)    
plt.show()