import turtle as tt
tt.pensize(3)
tt.color('blue')
tt.fillcolor('yellow')
tt.begin_fill()
tt.showturtle()
tt.forward(100)
tt.left(90)
tt.forward(100)
tt.left(90)
tt.forward(100)
tt.left(90)
tt.forward(100)
tt.hideturtle()
tt.end_fill()